workflows:
  flutter-build:
    name: Flutter Build Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter analyze
      - flutter build apk --release
      - flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing: 
      email:
        recipients:
          - alegomezrivas92@gmail.com
          - geiserarecio@gmail.com
        notify:
          success: true
          failure: false