workflows:
  flutter-build:
    name: Flutter Build Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter analyze
      - flutter build ios --release --no-codesign
      - flutter build apk --release --build-number=$PROJECT_BUILD_NUMBER \
        --obfuscate --split-debug-info=./symbols/debug_symbols_android \
        --extra-gen-snapshot-options=--save-obfuscation-map=./symbols/obfuscation_map \
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing: 
      email:
        recipients:
          - alegomezrivas92@gmail.com
          - geiserarecio@gmail.com
        notify:
          success: true
          failure: false